version: '3.9'
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network
  app:
    build: ./backend
    container_name: spring-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/testdb
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - app-network
volumes:
  mysql-data:
networks:
  app-network: